### ISSUE TITLE
Owner_id throws exception in some databases

### ISSUE THREAD

**Issue by juergmessmer** [rapila/cms-base#162]
Remove field if it is not used properly

**Comment by juergmessmer** [comment]
is this still an issue?

**Comment by sabberworm** [comment]
I don’t know.

**Comment by juergmessmer** [comment]
I guess this issue is fixed with commit 0836419410daf8ab05d5b9a7fd4981e523d6f556

by setting the default value to null
(owner_id was originally intended as part of a sophisticated owner handling that seems to be an overkill)
