### ISSUE TITLE
Implement BaseObject scheduling

### ISSUE THREAD

**Issue by sabberworm** [rapila/cms-base#195]
Right now we have a lot of `active_after` or `publish_date` fields. These are not very flexible and (for the most part) make efficient caching impossible.

The idea is to have a `scheduled_actions` table as follows:

| ID | Model name | Model key | Date | Action | Done |
| --- | --- | --- | --- | --- | --- |
| 1 | Pages | 3 | 31.12.2014 | publish | true |
| 2 | LanguageObject | 12_de | 11.12.2016 | publishDraft | false |

Then a Cron job could touch `/get_file/scheduler` every minute to launch the scheduler.
The scheduler would look at this table, and with every action whose date lies in the past and whose done flag is false, load the corresponding object into memory and call the action method on it, then saving it.
## What needs to be done?
- The scheduler needs to handle permissions correctly: the person who added the `scheduled_actions` entry should be the user whose permissions are being verified on save.
- Scheduled actions should be immutable and you should only be able to delete your own schedules.
- There would need to be a new propel behaviour for all models whose purpose it is to delete scheduled_actions on delete (or maybe we could just ignore them).
- The GUI should be just a button widget whose configuration options are model name and model key, where model key is the one returned by `getPKString()`. On click, it would display a dialog with a list of all scheduled actions for that object, ordered by date. To schedule a new action, there is a `+`-Button with submenus of all possible actions for that model. The list of possible actions is retrieved by naming convention `executeScheduled…`.
- Caching would continue to work as normal as long as we would take the `updated_at` into account for caching.
- We should add convenience methods to `CacheKey` like `dependOnModel` which would select the `updated_at` of the newest object in said model to check whether the cache is fresh or stale.
## Discuss
- Should there be actions with arguments (like `removeTag(name)`, `changeValueTo(newValue)` or `moveTo(top)`)? I think this is overly complex but could be really cool.

**Comment by juergmessmer** [comment]
I guess this is closed.
