### ISSUE TITLE
Login (/cms_login/) is reloading in a loop (widgetInformation.methods is undefined)

### ISSUE THREAD

**Issue by juergmessmer** [rapila/cms-base#234]
http://domain/cms_login/
Endless loop of reloading the page: js error thrown: loadInfo / widgetInformation.methods is undefined.

This occurred while testing a protected page with a non-admin/backend user, and was redirected to login.

**Comment by juergmessmer** [comment]
Logout goes to /cms_login/ too (since I hardly ever logout, I'm not sure, but wouldn't logout redirect to frontend?

**Comment by juergmessmer** [comment]
Still can't debug it. The only thing I know that admin_menu and documentation_display are instantiated in a loop, why? It's neither admin nor preview?

**Comment by sabberworm** [comment]
I’m not sure when we broke this but I think we introduced the reload loop when we added the reload if we get a `NotLoggedInException` (or whatever it’s called).

**Comment by juergmessmer** [comment]
You relate to commit https://github.com/rapila/cms-base/commit/ebad71c5fbca88f694ea354bfc85c8ef47dac86b ?

**Comment by sabberworm** [comment]
I think so

**Comment by sabberworm** [comment]
@juergmessmer Can you check if this is fixed now?

**Comment by juergmessmer** [comment]
The original issue is fixed.

But two behaviors are not quite the way they should be.
1. Admin logout redirects to cms_login instead of the last page used as before
2. A authenticated user that may view protected page is not redirected to login_referrer_page (remains in cms_login and displays logout link)

**Comment by juergmessmer** [comment]
I moved the position 2 (cms_login:redirect to referrer) to it's own issue #242, so this can be closed
