### ISSUE TITLE
Logout throws uncaught exception: [object Object]

### ISSUE THREAD

**Issue by juergmessmer** [rapila/cms-base#238]
It reloads immediately after the exception, but quickly shows the notification.
I tried to see where it happens, but could not figure out.

**Comment by sabberworm** [comment]
You can configure your browser console to persist logs/network across reloads, you’re more likely to catch it that way.

**Comment by juergmessmer** [comment]
It's "impossible" to debug this. 

The exception is thrown in WidgetJsonFileModule::checkPermissions()  > !Session::getSession()->isAuthenticated(). 

This doesn't happen in release-1.7. I guess it has something to do with the session handling?

This exception is always thrown at logout, but depending on the site I'm testing (both current master) , the following happens after the js/json exception

- In mosaics (old, more complex page)  > redirects to frontend page
- in cms-dev (new simple installation) > redirects to cms_login and redirects/reloads in a loop to the login manager (see #234) 
logout location.href is e.g. "/seite-1" (active, not protected) or "/"

I tried to debug this, but can't figure out. I tried to debug session, requests, managers, login window, login frontend module etc. but no chance!

I just know that
- If the user is not set to null in session logout this particular error doesn't occur
- after logout these files are loaded or action executed
   – login_window login_window and logout
   – login and destroy
   – and finally in a loop [documentation_display, admin_menu, login, destroy]... (referrer cms_login)

**Comment by sabberworm** [comment]
No font loading error would trigger a `notifyUser` call. But I have so far also been unable to debug this. As a stopgap, we could simply set `Widget.notifyUser` to `$.noop` on `beforeunload`.

**Comment by tgressly** [comment]
I think this is what triggers `Undefined index: session_key` in `/get_file/widget_json/-/destroy`

**Comment by tgressly** [comment]
I think this is what triggers `Undefined index: session_key` in `/get_file/widget_json/-/destroy`.

**Comment by sabberworm** [comment]
I think we fixed this in 2.0/master by removing the implementation of `destroy` in `WidgetJsonFileModule`. Reopen if it pops up again.
