### ISSUE TITLE
Admin list reorder sort by d&d doesn't work anymore

### ISSUE THREAD

**Issue by juergmessmer** [rapila/cms-base#245]
In both admin documents and links list.

Version: master, it still worked in release-1.7.

Assumed reason:
Introduction of hash_key must have broken this.

Observed:
As soon as you choose sort asc while a categeory is chosen, the sortable icons in the sort column disappear. (list.allowSort does return true!)

**Comment by juergmessmer** [comment]
I can't figure out what's really happening. 
If a category is chosen and the sort order is "sort" and "asc", the class .ui-sortable-handle is removed. It looks like it could be related to the update to jQuery 3. See this error when stopping on a breakpoint.

<img width="608" alt="screen shot 2018-07-05 at 07 03 25" src="https://user-images.githubusercontent.com/374433/42303470-c61774fe-8021-11e8-9fb3-886c52f05af1.png">

**Comment by sabberworm** [comment]
This error is completely unrelated. It’s a browser compatibility test done by the jQuery selector engine sizzle.

**Comment by juergmessmer** [comment]
Yes, I just noticed because it happens independently of module and sort order.

**Comment by juergmessmer** [comment]
I tried to further examine it, but havn't found out yet what it could be. When I look at the admin/widget/resources change history I can only imagine that it's somehow related to the hashkey changes (probably not?) or jquery/UI update. 

@sabberworm : It exceeds my debug capabilities... please have a look at it asap since sorting - particularly document (image galleries) - is widely used.

**Comment by sabberworm** [comment]
Fixed with fde3141
