### ISSUE TITLE
Document detail replace document/data doesn't work (particularly PDFs)

### ISSUE THREAD

**Issue by juergmessmer** [rapila/cms-base#250]
Situation when it occurs: 
Need to replace "content" image, pdf, etc. of an existing rapila document.
- open detail from list in admin/documents
- replace file with drag and drop

What happens is not intirely clear. 
It looks like this behavior concerns mainly PDFs. PDFs can't be replaced by another one. It's not properly stored. 
Note: this happened also with images in previous situations: when replacing a document content of a document stored in a media object. Since this happened rarely and was somehow resolved after clearing caches or even re-configuring the media object concerned, this "bug" was ignored at the time and never officially became an "issue".

Other observations
- also replacing a pdf documents file can store empty data in the related (new hash) data object. Once it's empty, there is no chance in changing it anymore. The file has to be deleted.

Summery
the first reason for deeper testing was the fact that in frontend document lists the update was not shown. Since I did not understand why pdfs should behave differently than images I was not concentrating on this. It still looks like any change of an already existing document can cause problems. But with PDFs it's very obvious. It doesn't look like this is a frontend or frontend caching problem but concerns only the handling of documents in admin.

**Comment by sabberworm** [comment]
For me this seems to work fine. The preview wasn’t updated after the save because of browser caching, this is fixed with 44f757e0.

Updating a document in a document list always worked correctly for me.
