### ISSUE TITLE
LinkUtil::isSSL() yields http instead of https in docker environments

### ISSUE THREAD

**Issue by tgressly** [rapila/cms-base#258]
`LinkUtil::isSSL()` yields `false` (http, port 80) instead of `true` (https) in some docker environments.

Within the `isSSL()` method the `$_SERVER`-variables return `http`, `80` respectively. I.e. there must be a place where the scripts are delivered via the http protocol. But where?  

`$_SERVER['SCRIPT_NAME']` is the front web controller: `index.php`.

This happens in givenmoments.com. Quick hacky workaround was to return true in any case.

All other rapila instances on the same server in the same branch (`master`) work as expected.

Suggestions?

**Comment by sabberworm** [comment]
Most proxies set `X-Forwarded-*` headers. I know træfik does. `X-Forwarded-Proto` is honored by `LinkUtil::isSSL` if the config option `general` → `trust_http_proxy_headers` is set to the value `"X-Forwarded"`.

BTW: I know I set this config correctly on `givenmoments.com` (and all of your other sites). Maybe you accidentally reverted that (I hadn’t committed it since we were on a tight schedule if I remember correctly)?

**Comment by tgressly** [comment]
I don’t see this “setting” anywhere? Where is it to be set? Thanks for your help.

**Comment by juergmessmer** [comment]
I guess in site/config/config.yml > general > trust_http_proxy_headers: true

**Comment by tgressly** [comment]
`frontend:
  trust_http_proxy_headers: 'X-Forwarded'`
Funktioniert aber nicht: https://www.givenmoments.com/de/the-purse

**Comment by juergmessmer** [comment]
Bevor ich gesehen habe, dass dieser Issue scheinbar gelöst ist, habe ich noch nach Infos über Serverseitige https detection gesucht und dies hier gefunden. Keine Ahnung, ob das hilft.

```
function isSecure() {
  return
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
    || $_SERVER['SERVER_PORT'] == 443;
}
```
https://stackoverflow.com/questions/1175096/how-to-find-out-if-youre-using-https-without-serverhttps

**Comment by juergmessmer** [comment]
@tgressly warum hast du dieses setting nicht unter general: gemacht, wie es im base konfiguriert ist?

**Comment by tgressly** [comment]
@juergmessmer Weil ich es so gesehen hatte in reginaschlager.ch, wo es ja läuft.

**Comment by juergmessmer** [comment]
@tgressly Ich verstehe dabei nicht, dass nur das Frontend secure sein sollte? Zudem wird ja in isSSL() das Setting wie folgt überprüft

`if(Settings::getSetting('general', 'trust_http_proxy_headers', false) === 'X-Forwarded') {}`

also eine frontend setting gar nicht berücksichtigt.

**Comment by sabberworm** [comment]
Wenn ich das mal kurz auflösen darf:

bei reginaschlager.ch funktionierts, weil zusätzlich

```yaml
linking:
  ssl_in_absolute_links: true
```

gesetzt ist.

Wahrscheinlich habe ich das hinzugefügt weil ich im Stress nicht gecheckt hatte, dass ich `trust_http_proxy_headers` in der falschen Section `frontend` statt `general` hinzugefügt hatte.

**Comment by tgressly** [comment]
In section `general` gehts. Super, danke!
