### ISSUE TITLE
Admin: configure template/pagetype fails in PHP 7.49

### ISSUE THREAD

**Issue by juergmessmer** [rapila/cms-base#260]
admin/page_detail>Trying to open the dialog for changing template/pagetype  fails.

A Javascript error is thrown `error min.js evaluating 'e.nodeName`, 
PHP 7.49 (running on remote server Metanet). After changing it back to 7.2 it worked without problem. 

It's hard for me to debug this because I don't see any other information and my local environment is not running on the same php version.

**Comment by sabberworm** [comment]
Weird. Why would a PHP error trigger a JavaScript error? Is the server sending an unexpected response?

**Comment by juergmessmer** [comment]
It was the only error I have seen, no request and response that seemed to throw an error. 
Do you have a installation of rapila at hand, running on a 7.4+  or 7.49 PHP version? Could you check whether you have the same problem? (Just open template/pagetype)

As soon as I have the time and peace to change it back again to 7.49, I'll try to figure out a little more.

**Comment by juergmessmer** [comment]
Today I switched my php to 7.49 again, just for testing it again, and there was no problem, no js error. So I guess it was just a bad day of "something" or "someone" :-)
